
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bilal Ahmad
 */
public class CurrentAccess extends javax.swing.JFrame implements Serializable {

    /**
     * Creates new form CurrentAccess
     */
     static String n;
     static Account h;
     Account ac;
    public CurrentAccess(Account ac) 
    {
         initComponents();
      h=ac;
      this.ac=ac;
        name.setText(ac.Name);
        balance.setText(""+ac.Balance+"Rs");
        type.setText(ac.AccountType);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        balance = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        paise = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Deposit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        deposit = new javax.swing.JLabel();
        withdraw = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("Welcome to Bank");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 57, 202, 79));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("HI,");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 30, -1));

        name.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        name.setText("some");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 240, 35));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("Your Account Type is : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 129, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setText("Your Current Balance is :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 176, -1, -1));

        balance.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        balance.setText("balance");
        getContentPane().add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 173, 140, 22));

        type.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        type.setText("type");
        getContentPane().add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 130, 160, 16));

        paise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paiseActionPerformed(evt);
            }
        });
        getContentPane().add(paise, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 259, 157, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel5.setText("Enter Amount");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 257, 98, 25));

        Deposit.setText("Depsoit");
        Deposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositActionPerformed(evt);
            }
        });
        getContentPane().add(Deposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jButton2.setText("Withdraw");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 370, -1, -1));
        getContentPane().add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 200, 30));
        getContentPane().add(deposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 220, 50));
        getContentPane().add(withdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 240, 60));

        jButton1.setText("Sign Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paiseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paiseActionPerformed

    private void DepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositActionPerformed
        error.setText("");
        deposit.setText("");
        withdraw.setText("");
        ac.Deposit(Float.parseFloat(paise.getText()));
          balance.setText(""+ac.Balance);
          deposit.setText("You just deposit "+Float.parseFloat(paise.getText())+" Rs ");
    }//GEN-LAST:event_DepositActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      error.setText("");
      withdraw.setText("");
      deposit.setText("");
        int n=ac.Withdraw(Float.parseFloat(paise.getText()));
       if(n==0)
       {
           error.setText("You can't withdraw money more than Your balance");
       
       }
       else{
           balance.setText(""+ac.Balance);
           withdraw.setText("You just Withdew "+Float.parseFloat(paise.getText())+" Rs");
       }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
            FileOutputStream ac= new FileOutputStream ( "Save.txt");
            ObjectOutputStream ob = new ObjectOutputStream(ac);
            ob.writeObject(Account.accountlist);
            ob.flush();
            ob.close();
            
        }
        catch( IOException e)
        {
            System.out.println("not successful");
        }
        try
        {
            FileInputStream sc=new FileInputStream("Save.txt");
            ObjectInputStream dc= new ObjectInputStream(sc);
            ArrayList<Account> arr= (ArrayList<Account>) dc.readObject();
            for (int i=0; i<arr.size(); i++)
                {
                         System.out.println("account number is: "+ arr.get(i).AccountNumber + " Name is: " +arr.get(i).Name + " Address is: " + arr.get(i).Address + " NIC " + arr.get(i).NIC);
                }
        }
        catch(IOException e)
                {
                    System.out.println("not succesful");
                } 
        catch (ClassNotFoundException ex) 
        {
             Logger.getLogger(CurrentAccess.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        AccountOpen o = new AccountOpen();
        o.show();
        this.hide();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrentAccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrentAccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrentAccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrentAccess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrentAccess(h).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Deposit;
    private javax.swing.JLabel balance;
    private javax.swing.JLabel deposit;
    private javax.swing.JLabel error;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel name;
    private javax.swing.JTextField paise;
    private javax.swing.JLabel type;
    private javax.swing.JLabel withdraw;
    // End of variables declaration//GEN-END:variables
}
